### ISSUE TITLE
Handle container redeploy

### ISSUE THREAD

**Issue by dransome** [layershift/jps-strongswan#1]
We need to add event handlers for [onBeforeRedeployContainer](http://docs.cloudscripting.com/creating-manifest/events/#onbeforeredeploycontainer) / [onAfterRedeployContainer](http://docs.cloudscripting.com/creating-manifest/events/#onafterredeploycontainer) to ensure VPN configuration / connectivity does not get lost when switching container version (e.g. updating to different MySQL release or similar).

**Comment by rauladorean** [comment]
Fixed by removing nodeGroupAlias
